(import (class com.badlogic.gdx Gdx Screen)
        (class com.badlogic.gdx.graphics GL20 Texture)
        (class com.badlogic.gdx.graphics.g2d SpriteBatch))

(define-simple-class org.libgdx.example.MyScreen (Screen)
  (batch ::SpriteBatch)
  (image ::Texture)
  ((show)
   (set! batch (make SpriteBatch))
   (set! image (make Texture "badlogic.jpg")))
  ((render delta ::float)
   (Gdx:gl:glClearColor 1.0 0.0 0.0 0.0)
   (Gdx:gl:glClear (bitwise-ior GL20:GL_COLOR_BUFFER_BIT
                                GL20:GL_DEPTH_BUFFER_BIT))
   (batch:begin)
   (batch:draw image 0.0 0.0)
   (batch:end))
  ((dispose) ())
  ((hide) ())
  ((pause) ())
  ((resize width ::int height ::int) ())
  ((resume) ()))
